version: "3"
## front:v2 has backend url as: http://localhost/api
## otherwise it is the same
## added REDIS_HOST=redis to Dockerfile
services:
  front:
    image: front:v2
    ports:
      - 5000:5000
    build: .
  back:
    image: back
    ports:
      - 8080:8080
    build: .
    environment:
      - POSTGRES_HOST=postgres
  redis:
    image: redis
    ports:
      - 6379:6379
    build: .
  postgres:
    image: postgres
    ports:
      - 5432:5432
    build: .
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

volumes:
  database: